-- A second exposed schema for the schema-selection integration tests,
-- deliberately reusing a table name from the public schema so the tests can
-- prove a request reached the schema the client selected.
-- RLS matches 0_schema.sql: anonymous read, exercising the anon-role path a
-- real consumer's publishable key uses.

create schema personal;
grant usage on schema personal to anon;

create table personal.instruments (
    id bigint generated by default as identity primary key,
    name text not null,
    acquired_year integer
);
alter table personal.instruments enable row level security;
create policy "anonymous can read instruments" on personal.instruments for select to anon using (true);
grant select on table personal.instruments to anon;

-- A function that lives only in the personal schema, so a schema-selected RPC
-- resolves here while the same call against the default schema does not.
create function personal.count_instruments() returns bigint
    language sql stable
    as $$ select count(*) from personal.instruments $$;
grant execute on function personal.count_instruments() to anon;
