-- Schema for the SDK integration tests, applied by the CLI on stack start
-- before seed.sql. Schema lives here rather than in the seed because the CLI
-- sends seed.sql as a single batch, in which statements are prepared before
-- earlier ones execute - so DDL cannot ride with inserts that depend on it.
-- RLS is enabled with an anonymous-read policy so the tests exercise the same
-- anon-role path a real consumer's publishable key uses.
create table public.instruments (
    id bigint generated by default as identity primary key,
    name text not null
);

alter table public.instruments enable row level security;

create policy "anonymous can read instruments"
    on public.instruments for select
    to anon
    using (true);

-- RLS policies filter rows but grant nothing: without the table privilege the
-- anon role gets "permission denied" (42501), policy or not. The CLI
-- repository's own e2e migration grants explicitly for the same reason.
grant select on table public.instruments to anon;
