-- Schema for the Go SDK integration tests, applied by Supabase stack start
-- before seed.sql.
-- RLS is enabled with an anonymous-read policy so the tests exercise the same
-- anon-role path a real consumer's publishable key uses.

create table public.instruments (
    id bigint generated by default as identity primary key,
    name text not null,
    acquired_year integer
);
alter table public.instruments enable row level security;
create policy "anonymous can read instruments" on public.instruments for select to anon using (true);
grant select on table public.instruments to anon;

create table public.players (
    id integer not null primary key,
    section integer not null,
    seat integer not null,
    rating integer,
    tenure integer
);
alter table public.players enable row level security;
create policy "anonymous can read players" on public.players for select to anon using (true);
grant select on table public.players to anon;

create table public.sequences (
    id integer not null primary key,
    "decimal number" character(2) not null,
    character character(1) not null,
    phonetic text not null
);
alter table public.sequences enable row level security;
create policy "anonymous can read sequences" on public.sequences for select to anon using (true);
grant select on table public.sequences to anon;

-- Table names as a delimited identifier (a.k.a. quoted identifier), meaning:
-- - they're case sensitive
-- - they can contain any character (exception the character with code zero)
-- https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

create table public."odd table" (id integer not null primary key, name text not null);
alter table public."odd table" enable row level security;
create policy "anonymous can read odd table" on public."odd table" for select to anon using (true);
grant select on table public."odd table" to anon;

create table public."a?b" (id integer not null primary key, name text not null);
alter table public."a?b" enable row level security;
create policy "anonymous can read a?b" on public."a?b" for select to anon using (true);
grant select on table public."a?b" to anon;

create table public."rpc/d" (id integer not null primary key, name text not null);
alter table public."rpc/d" enable row level security;
create policy "anonymous can read rpc/d" on public."rpc/d" for select to anon using (true);
grant select on table public."rpc/d" to anon;

create table public."hello//world" (id integer not null primary key, name text not null);
alter table public."hello//world" enable row level security;
create policy "anonymous can read hello//world" on public."hello//world" for select to anon using (true);
grant select on table public."hello//world" to anon;

create table public."/leading" (id integer not null primary key, name text not null);
alter table public."/leading" enable row level security;
create policy "anonymous can read /leading" on public."/leading" for select to anon using (true);
grant select on table public."/leading" to anon;

create table public."trailing/" (id integer not null primary key, name text not null);
alter table public."trailing/" enable row level security;
create policy "anonymous can read trailing/" on public."trailing/" for select to anon using (true);
grant select on table public."trailing/" to anon;

create table public."e&f" (id integer not null primary key, name text not null);
alter table public."e&f" enable row level security;
create policy "anonymous can read e&f" on public."e&f" for select to anon using (true);
grant select on table public."e&f" to anon;

create table public."." (id integer not null primary key, name text not null);
alter table public."." enable row level security;
create policy "anonymous can read ." on public."." for select to anon using (true);
grant select on table public."." to anon;

create table public.".." (id integer not null primary key, name text not null);
alter table public.".." enable row level security;
create policy "anonymous can read .." on public.".." for select to anon using (true);
grant select on table public.".." to anon;

create table public."../.." (id integer not null primary key, name text not null);
alter table public."../.." enable row level security;
create policy "anonymous can read ../.." on public."../.." for select to anon using (true);
grant select on table public."../.." to anon;

create table public."g/../h" (id integer not null primary key, name text not null);
alter table public."g/../h" enable row level security;
create policy "anonymous can read g/../h" on public."g/../h" for select to anon using (true);
grant select on table public."g/../h" to anon;

create table public."50%off" (id integer not null primary key, name text not null);
alter table public."50%off" enable row level security;
create policy "anonymous can read 50%off" on public."50%off" for select to anon using (true);
grant select on table public."50%off" to anon;

create table public."""" (id integer not null primary key, name text not null);
alter table public."""" enable row level security;
create policy "anonymous can read """ on public."""" for select to anon using (true);
grant select on table public."""" to anon;

create table public."'" (id integer not null primary key, name text not null);
alter table public."'" enable row level security;
create policy "anonymous can read '" on public."'" for select to anon using (true);
grant select on table public."'" to anon;

create table public."`" (id integer not null primary key, name text not null);
alter table public."`" enable row level security;
create policy "anonymous can read `" on public."`" for select to anon using (true);
grant select on table public."`" to anon;

create table public."2026-06-30T11:23:31" (id integer not null primary key, name text not null);
alter table public."2026-06-30T11:23:31" enable row level security;
create policy "anonymous can read 2026-06-30T11:23:31" on public."2026-06-30T11:23:31" for select to anon using (true);
grant select on table public."2026-06-30T11:23:31" to anon;

create table public."a+b" (id integer not null primary key, name text not null);
alter table public."a+b" enable row level security;
create policy "anonymous can read a+b" on public."a+b" for select to anon using (true);
grant select on table public."a+b" to anon;

-- A table with rows that have values which include reserved characters.
create table public."⚠ reserved ⚠" (
    name text not null primary key,
    text text not null,
    "array" text[] not null
);
alter table public."⚠ reserved ⚠" enable row level security;
create policy "anonymous can read ⚠ reserved ⚠" on public."⚠ reserved ⚠" for select to anon using (true);
grant select on table public."⚠ reserved ⚠" to anon;

create table public.issues (
    id integer not null primary key,
    title text not null,
    status text not null,
    priority integer not null,
    effort double precision not null,
    resolved boolean,
    assignee text,
    tags text[] not null,
    metadata jsonb,
    active_during tstzrange,
    created_at timestamp with time zone not null,
    search tsvector
);
alter table public.issues enable row level security;
create policy "anonymous can read issues" on public.issues for select to anon using (true);
grant select on table public.issues to anon;

-- The Menagerie, where:
-- - each table is a family of data types who share similar characteristics
-- - some families only have one member, and that's ok

create table public."🦁 raw"
(
    name text not null primary key,
    "byte array" bytea
);
alter table public."🦁 raw" enable row level security;
create policy "anonymous can read 🦁 raw" on public."🦁 raw" for select to anon using (true);
grant select on table public."🦁 raw" to anon;

create table public."🦁 UUID"
(
    name text not null primary key,
    "universally unique identifier" uuid
);
alter table public."🦁 UUID" enable row level security;
create policy "anonymous can read 🦁 UUID" on public."🦁 UUID" for select to anon using (true);
grant select on table public."🦁 UUID" to anon;

create type public."🦁 emotions" as enum (
    -- https://www.postgresql.org/docs/current/datatype-enum.html#DATATYPE-ENUM-ORDERING:
    -- "The ordering of the values in an enum type is the order in which the values were listed when the type was created."
    '😨',
    'weltschmerz',
    '😢',
    'torschlusspanik',
    '😡',
    '😮',
    'fremdschämen',
    'schadenfreude',
    '😀'
);

create table public."🦁 emotion"
(
    name text not null primary key,
    emotion public."🦁 emotions"
);
alter table public."🦁 emotion" enable row level security;
create policy "anonymous can read 🦁 emotion" on public."🦁 emotion" for select to anon using (true);
grant select on table public."🦁 emotion" to anon;

-- A deliberately slow relation for proving client-side timeouts
-- (pg_sleep sits in the from list as a function scan, so it runs once per
-- statement, not once per row). Views cannot enable row level security of
-- their own, so security_invoker makes reads run with the caller's rights.
create view public.slow_instruments with (security_invoker = true) as
    select instruments.* from public.instruments, pg_sleep(2);
grant select on table public.slow_instruments to anon;

-- A writable table for the mutation integration tests: anon holds every verb
-- so tests exercise the same publishable-key path a real consumer uses. The
-- identity and defaulted columns let returned representations prove
-- server-filled values, and tests own their rows by unique title.
create table public.repertoire (
    id bigint generated always as identity primary key,
    title text not null unique,
    composer text,
    difficulty integer not null default 3
);
alter table public.repertoire enable row level security;
create policy "anonymous full access to repertoire" on public.repertoire
    for all to anon using (true) with check (true);
grant select, insert, update, delete on table public.repertoire to anon;
grant usage on sequence public.repertoire_id_seq to anon;

-- Insert-only for anon: allows us to test the documented RLS interaction where
-- a mutation succeeds with a minimal return yet fails with 42501 when a
-- representation is requested, because the RETURNING a representation needs
-- requires SELECT rights the anon role does not hold.
create table public.suggestion_box (
    id integer not null primary key,
    suggestion text not null
);
alter table public.suggestion_box enable row level security;
create policy "anonymous can insert suggestions" on public.suggestion_box
    for insert to anon with check (true);
grant insert on table public.suggestion_box to anon;

-- A second writable table for the upsert integration tests: a natural primary
-- key (sku) plus a secondary unique column (barcode) let the tests target both
-- the default conflict target and an explicit on_conflict, while name carries
-- no unique constraint so a mistargeted on_conflict proves the 42P10 path.
-- anon holds every verb, exercising the same publishable-key path a consumer
-- uses.
create table public.products (
    sku text not null primary key,
    barcode text unique,
    name text not null,
    price integer not null
);
alter table public.products enable row level security;
create policy "anonymous full access to products" on public.products
    for all to anon using (true) with check (true);
grant select, insert, update, delete on table public.products to anon;

-- Functions for the RPC integration tests, one per result shape and transport.
-- All default to SECURITY INVOKER and public EXECUTE, so a call runs with the
-- caller's rights and the anon table policies above keep applying. The
-- volatility markers matter: immutable and stable functions also run under GET
-- (read-only), while the volatile one may only be called through a POST.

-- Scalar result: add_them answers a bare integer, decoded through CollectRaw.
create function public.add_them(a integer, b integer)
returns integer language sql immutable as 'select a + b;';

-- Scalar result with a defaulted parameter: greet answers text and, called with
-- no arguments, takes its default so the empty-object body reaches the default.
create function public.greet(name text default 'world')
returns text language sql immutable as $$ select 'hello ' || name; $$;

-- Single unnamed json parameter: sum_json receives the whole request body as
-- its one unnamed argument and sums the value field of each element. PostgREST
-- accepts an array body only when every element carries one shared key set, so
-- callers send [{"value":3},{"value":4}]-shaped arrays.
create function public.sum_json(json)
returns integer language sql immutable
as $$ select sum((element->>'value')::integer)::integer from json_array_elements($1) as t(element); $$;

-- Table-valued result: repertoire_easier_than returns a set of repertoire rows,
-- decoded like a table read. Stable, so it also runs read-only under GET.
create function public.repertoire_easier_than(max_difficulty integer)
returns setof public.repertoire language sql stable
as $$ select * from public.repertoire where difficulty < max_difficulty; $$;

-- Void result: void_function returns nothing, applied through Execute.
create function public.void_function()
returns void language plpgsql as $$ begin end; $$;

-- Volatile table-valued result: raise_difficulty writes and returns the changed
-- rows. Volatile, so PostgREST rejects it under a read-only GET.
create function public.raise_difficulty(piece_title text)
returns setof public.repertoire language sql volatile
as $$
    update public.repertoire set difficulty = difficulty + 1
    where title = piece_title returning *;
$$;
