-- Schema for the Go SDK integration tests, applied by Supabase stack start
-- before seed.sql.
-- RLS is enabled with an anonymous-read policy so the tests exercise the same
-- anon-role path a real consumer's publishable key uses.

create table public.instruments (
    id bigint generated by default as identity primary key,
    name text not null
);

alter table public.instruments enable row level security;

create policy "anonymous can read instruments"
    on public.instruments for select
    to anon
    using (true);

grant select on table public.instruments to anon;
