name: Validate SDK Compliance

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: supabase/sdk/.github/workflows/validate-sdk-compliance-go.yml@5bd367cd2a88a1d99ed3060154069caf0381d5ff # capability-matrix/v1.13.0
