name: Validate SDK Compliance

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: supabase/sdk/.github/workflows/validate-sdk-compliance-go.yml@75cf587c486f80c2d2afe57ec909ee2520c098b9 # v1.5.0
