name: Validate SDK Compliance

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: supabase/sdk/.github/workflows/validate-sdk-compliance-go.yml@7ea18703f9148439941454238f2ee03012bae24b # v1.4.0
